apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-webcolor
  namespace: argocd
  labels:
    curso: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/wesleymlopes/web-page-deploy.git
    targetRevision: HEAD
    directory:
      recurse: true
      exclude: 'nginx/*'
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: webcolor
  info:
    - name: "app"
      value: "webcolor"
    - name: "team"
      value: "devops"
    - name: Projeto
      value: "projeto argocd curso devopspro"