apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 29.35.0
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/prometheus/values.yaml
    - repoURL: https://github.com/wesleymlopes/web-page-deploy.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoramento