apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: conversao-temperatura
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wesleymlopes/web-page-deploy.git
    targetRevision: HEAD
    path: kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: conversao-temperatura